"""Added created_at column to plants

Revision ID: 1c725bcc82a2
Revises: 
Create Date: 2025-02-22 09:21:13.971103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c725bcc82a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add new column with a nullable state first
    op.add_column('plants', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Set default datetime for existing records
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE plants SET created_at = now() WHERE created_at IS NULL")
    )

    # Make the column non-nullable
    op.alter_column('plants', 'created_at', nullable=False, server_default=sa.func.now())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('created_at')
